modLoader="javafml"
loaderVersion="[47,)"
license="Academic Free License v3.0"

[[mods]]
modId="epic_core_api"
version="1.20.11.0.0"
displayName="Epic Core API"
displayURL="https://github.com/CJiangqiu/Epic-Core-API-Remote-Workspace"
logoFile="logo.png"
credits="Procedure:CJiangqiu;Mascot:Mcreator"
authors="CJiangqiu"
description="This is an API mod created by CJiangqiu"

[[dependencies.epic_core_api]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1]"
    ordering="NONE"
    side="BOTH"



[[dependencies.epic_core_api]]
    modId="jade"
    mandatory=false
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"

